### ISSUE TITLE
Chapter for Cloud Object Storage template in Bluemix Docs

### ISSUE THREAD

**Issue by beemarie** [ibm-functions/template-cloud-object-storage#19]
2 sections:
- deploy with the CLI
... deploy package
... bx service bind
... deploy template
... open app in browser. (update avatar pic with COS)
- deploy with the UI

**Comment by eweiter** [comment]
This is being handled in PR https://github.ibm.com/Bluemix-Docs/openwhisk/pull/183

**Comment by eweiter** [comment]
This is in staging now.
